# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DefaultUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 256, 551))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.verticalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(235, 27, 20, 521))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName(_fromUtf8("verticalScrollBar"))
        self.horizontalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(3, 531, 230, 20))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(260, 0, 531, 551))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.columnView = QtGui.QColumnView(self.frame)
        self.columnView.setGeometry(QtCore.QRect(-5, 0, 541, 551))
        self.columnView.setAutoFillBackground(True)
        self.columnView.setStyleSheet(_fromUtf8("background : rgb(f,f,f)"))
        self.columnView.setObjectName(_fromUtf8("columnView"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuView_mode = QtGui.QMenu(self.menuView)
        self.menuView_mode.setObjectName(_fromUtf8("menuView_mode"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuVirtual = QtGui.QMenu(self.menubar)
        self.menuVirtual.setObjectName(_fromUtf8("menuVirtual"))
        self.menuShell = QtGui.QMenu(self.menubar)
        self.menuShell.setObjectName(_fromUtf8("menuShell"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_directory = QtGui.QAction(MainWindow)
        self.actionNew_directory.setObjectName(_fromUtf8("actionNew_directory"))
        self.actionNewFile = QtGui.QAction(MainWindow)
        self.actionNewFile.setObjectName(_fromUtf8("actionNewFile"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionFind = QtGui.QAction(MainWindow)
        self.actionFind.setObjectName(_fromUtf8("actionFind"))
        self.actionTutorial = QtGui.QAction(MainWindow)
        self.actionTutorial.setObjectName(_fromUtf8("actionTutorial"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExtra_large_icons = QtGui.QAction(MainWindow)
        self.actionExtra_large_icons.setObjectName(_fromUtf8("actionExtra_large_icons"))
        self.actionExtra_large_icon = QtGui.QAction(MainWindow)
        self.actionExtra_large_icon.setObjectName(_fromUtf8("actionExtra_large_icon"))
        self.actionLarge_icons = QtGui.QAction(MainWindow)
        self.actionLarge_icons.setObjectName(_fromUtf8("actionLarge_icons"))
        self.actionMedium_icons = QtGui.QAction(MainWindow)
        self.actionMedium_icons.setObjectName(_fromUtf8("actionMedium_icons"))
        self.actionSmall_icons = QtGui.QAction(MainWindow)
        self.actionSmall_icons.setObjectName(_fromUtf8("actionSmall_icons"))
        self.actionList = QtGui.QAction(MainWindow)
        self.actionList.setObjectName(_fromUtf8("actionList"))
        self.actionNew_directory_2 = QtGui.QAction(MainWindow)
        self.actionNew_directory_2.setObjectName(_fromUtf8("actionNew_directory_2"))
        self.actionVirtual_drive = QtGui.QAction(MainWindow)
        self.actionVirtual_drive.setObjectName(_fromUtf8("actionVirtual_drive"))
        self.actionOpen_shell = QtGui.QAction(MainWindow)
        self.actionOpen_shell.setObjectName(_fromUtf8("actionOpen_shell"))
        self.actionRestart_shell = QtGui.QAction(MainWindow)
        self.actionRestart_shell.setObjectName(_fromUtf8("actionRestart_shell"))
        self.menuFile.addAction(self.actionNew_directory)
        self.menuFile.addAction(self.actionNewFile)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionFind)
        self.menuView_mode.addAction(self.actionExtra_large_icon)
        self.menuView_mode.addAction(self.actionLarge_icons)
        self.menuView_mode.addAction(self.actionMedium_icons)
        self.menuView_mode.addAction(self.actionSmall_icons)
        self.menuView_mode.addAction(self.actionList)
        self.menuView.addAction(self.menuView_mode.menuAction())
        self.menuHelp.addAction(self.actionTutorial)
        self.menuHelp.addAction(self.actionAbout)
        self.menuVirtual.addAction(self.actionNew_directory_2)
        self.menuVirtual.addAction(self.actionVirtual_drive)
        self.menuVirtual.addSeparator()
        self.menuShell.addAction(self.actionOpen_shell)
        self.menuShell.addAction(self.actionRestart_shell)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuShell.menuAction())
        self.menubar.addAction(self.menuVirtual.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "PC", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "New Item", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "New Subitem", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "New Subitem", None))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "New Subitem", None))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "New Item", None))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(0, _translate("MainWindow", "New Item", None))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "New Subitem", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuView_mode.setTitle(_translate("MainWindow", "View mode", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuVirtual.setTitle(_translate("MainWindow", "Virtual", None))
        self.menuShell.setTitle(_translate("MainWindow", "Shell", None))
        self.actionNew_directory.setText(_translate("MainWindow", "New directory", None))
        self.actionNewFile.setText(_translate("MainWindow", "NewFile", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionCut.setText(_translate("MainWindow", "Cut", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))
        self.actionDelete.setText(_translate("MainWindow", "Delete", None))
        self.actionUndo.setText(_translate("MainWindow", "Undo", None))
        self.actionFind.setText(_translate("MainWindow", "Find", None))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionExtra_large_icons.setText(_translate("MainWindow", "Extra large icons", None))
        self.actionExtra_large_icon.setText(_translate("MainWindow", "Extra large icons", None))
        self.actionLarge_icons.setText(_translate("MainWindow", "Large icons", None))
        self.actionMedium_icons.setText(_translate("MainWindow", "Medium icons", None))
        self.actionSmall_icons.setText(_translate("MainWindow", "Small icons", None))
        self.actionList.setText(_translate("MainWindow", "List", None))
        self.actionNew_directory_2.setText(_translate("MainWindow", "New directory", None))
        self.actionVirtual_drive.setText(_translate("MainWindow", "Virtual drive", None))
        self.actionOpen_shell.setText(_translate("MainWindow", "Open shell", None))
        self.actionRestart_shell.setText(_translate("MainWindow", "Restart shell", None))

